### ISSUE TITLE
SeATPlus not reachable after install

### ISSUE THREAD

**Issue by kaylak4520** [seatplus/seatplus#3]
**Describe the bug**
I'm back (Sorry)
After following the instructions after you fixed the previous ticket (https://github.com/seatplus/seatplus/issues/2) I can now complete the setup, however, the SeATPlus node container does not stay running, and I cannot access the UI (Too many redirects) 
I've looked through the documentation and don't see anything that says the Node service should remain stopped, so I'm assuming the 2 behaviours are related.

**To Reproduce**
1. Follow the install instructions
2. run "docker container ls" and notice the node container isn't present
3. Running "docker-compose logs --tail 10 -f" shows seatplus_node_1 exited with code 0
4. Navigating to the URL programmed (seatplus.syndicate-alliance.net) gives a too many redirects error

**Expected behavior**
To be accessible and running correctly

**Desktop (please complete the following information):**
 - OS: Ubuntu Server 22.04
 - 
**Additional context**
I've attached the output of docker-compose logs --tail 10 -f
I've also turned on APP_DEBUG=true however, I don't see anything different in the logging or any change in behavour
[dlogs.log](https://github.com/seatplus/seatplus/files/10972896/dlogs.log)

**Comment by herpaderpaldent** [comment]
If you prefer a more direct conversation i have a discord instance as well.

This behaviour is correct. Node is only needed to compile the assets once for production and again everytime a new update is available. Once run, node should exist.

Hence your issue seems to be between the proxy and the php container. Is there any insight on the php container? (it runs php-fpm + nginx).

Something i note on your logs:

1. You might have a permission issue with the storage folder. Have you executed `chown -R 1000:1000 src` ?
2. A CharacterAffiliationJob has been dispatched, so it seems something is running. Where exactly are you experiencing to many redirects?

**Comment by herpaderpaldent** [comment]
I allow myself to reference your finding in discord:

<img width="665" alt="grafik" src="https://user-images.githubusercontent.com/6583519/225241927-f56bc2c8-1a06-44e0-a738-47cfb944da8c.png">

Maybe i am misunderstanding [jaydrogers](https://github.com/jaydrogers) (The maintainer of the docker image i am using) in his explanation:
[https://github.com/serversideup/docker-php/issues/57#issuecomment-1254217287](https://github.com/serversideup/docker-php/issues/57#issuecomment-1254217287)

I was under the impression that for productive environment setup one must not differ from the default value. However seems the SSL_MODE seems to cause issues in both dev and prod. I opted to disable it by default in the referenced PR
