### ISSUE TITLE
Mumble server connector

### ISSUE THREAD

**Issue by Froobish** [seatplus/seatplus#7]
I need to be able to connect this to Mumble with authed characters via Seatplus.

**Comment by herpaderpaldent** [comment]
Thank you for your inquiry, **froobish**! 😊

While **seatplus** currently does not have plans to directly support Mumble integration, I have some exciting news for you: **Discord support** is on the horizon! 🎉

Here's what you can expect:

1. **Notifications**: Notifiactions for users to opt-in based on access group membership

2. **Channel Management**: Have discord channels managed or not: you decide. The plugin will add members based on their access group memberships for designated channels

Feel free to keep an eye out for the upcoming release, and if you have any further questions or need assistance, don't hesitate to reach out. Happy recruiting, and may your alliance thrive! 🚀🌟

**Comment by Froobish** [comment]
Hey. Thanks for the reply and apologies about the time between responses. Do you think that a Mumble connector will ever be something you'd add into it? Seatplus is so shiny and well-made, but Mumble is required which makes it difficult to use for an alliance like mine.

**Comment by herpaderpaldent** [comment]
Hey there!

Thank you so much for reaching out and for your suggestion regarding the integration of Mumble into seatplus. Your interest and proactive approach to enhancing the tool are genuinely appreciated!

After a thorough review and consideration, it appears that integrating Mumble directly into seatplus poses some significant challenges at the moment, primarily due to the lack of an accessible API or a straightforward method for application-based interaction with Mumble.

However, your input is incredibly valuable to me, and it’s these kinds of conversations that help shape the future of seatplus. While i might not be able to move forward with this particular integration right now, i'm always on the lookout for new ways to enhance the platform and support the community. 

Please don’t hesitate to bring up any other ideas or feedback you might have! I am committed to making seatplus the best it can be, and I'd love to explore more ways to make it even more useful for our users. 

Thanks again for your understanding and your contribution to the seatplus community. Let’s keep the conversation going!

Warm regards,
